/* The code points the runtime's root-locale collation table covers
 * (packages/runtime/src/scr_collation_data.h, generated by
 * scripts/gen-collation-table.mjs): ASCII controls TAB–CR and printable
 * ASCII, Latin-1 Supplement and Latin Extended-A except the vulgar
 * fractions, and the combining diacritical marks U+0300–U+0362. Text
 * outside this set compares by code point natively. */
export function isCollationCovered(text: string): boolean {
  for (const ch of text) {
    const c = ch.codePointAt(0)!;
    const covered =
      (c >= 0x09 && c <= 0x0d) ||
      (c >= 0x20 && c <= 0x7e) ||
      (c >= 0xa0 && c <= 0x17f && c !== 0xbc && c !== 0xbd && c !== 0xbe) ||
      (c >= 0x300 && c <= 0x362);
    if (!covered) return false;
  }
  return true;
}
