import type { IrLibFn } from "./builtin-signatures.js";

/** The may-throw seed: libCall members that can raise. Every fs.* member
 * EXCEPT existsSync (which, like Node's, swallows errors and returns false)
 * throws a catchable error on failure; json.parse throws a catchable
 * SyntaxError-shaped string on malformed input. Backends' may-throw analyses must treat a function containing one
 * of these as throwing, exactly like a `throw` statement (and must ALSO
 * seed on `dynCheck` and `awaitExpr` nodes, which throw on validation
 * failure / promise rejection). */
export const MAY_THROW_LIB_FNS: ReadonlySet<IrLibFn> = new Set([
  "text.encodeInto",
  "buffer.isAscii",
  "buffer.isUtf8",
  "buffer.transcode",
  "cp.spawnDynamic",
  "child.onDyn",
  "text.decoderEncoding",
  "dyn.construct",
  "dyn.reflectApply",
  "dyn.reflectGet",
  "dyn.reflectSet",
  "dyn.reflectDefine",
  "dyn.abstractEq",
  "text.decodeOptions",
  "text.decodeStream",
  "text.decodeLegacyOptions",
  "dyn.nativeSetNew",
  "ffi.argument",
  "ffi.memoryModule",
  "process.stdoutWrite",
  "process.stderrWrite",
  "process.stdoutWriteBytes",
  "process.stderrWriteBytes",
  "procStream.write",
  "weakMap.new",
  "weakSet.new",
  "dyn.fromEntries",
  "bytes.constructor",
  "bytes.instanceOf",
  "buffer.byteLenDyn",
  "bytes.construct",
  "arrayBuffer.new",
  "arrayBuffer.byteLengthGetter",
  "arrayBuffer.viewU8C",
  "arrayBuffer.viewI8",
  "arrayBuffer.viewU16",
  "arrayBuffer.viewI16",
  "arrayBuffer.viewU8",
  "arrayBuffer.viewU32",
  "arrayBuffer.viewI32",
  "arrayBuffer.viewF32",
  "arrayBuffer.viewF64",
  "arrayBuffer.viewDV",
  "bytes.bufferSource",
  "text.decodeBufferSource",

  "bigint.parse",
  "bigint.fromF64",
  "bigint.div",
  "bigint.mod",
  "bigint.pow",
  "bigint.shl",
  "bigint.shr",
  "bigint.toString",
  "bigint.asUintN",
  "bigint.asIntN",
  "bigint.bufferRead",
  "bigint.bufferWrite",
  "bigint.dataViewGet",
  "bigint.dataViewSet",
  "fetch.requestNew",
  "fetch.headersNew",
  "fetch.responseNew",
  "fetch.abortTimeout",
  "fetch.abortAny",
  "abort.timeout",
  "abort.any",
  "fetch.streamNew",
  "fetch.streamFrom",
  "num.toFixed",
  "num.toStringRadix",
  "insp.jsonDyn",
  // diagnostics_channel: publish runs subscribers synchronously (a throw
  // propagates — the documented divergence from triggerUncaughtException);
  // the subscribe/unsubscribe forms throw Node's ERR_INVALID_ARG_TYPE for
  // non-function subscribers.
  "dc.publish",
  "dc.subscribe",
  "dc.unsubscribe",
  "dc.chanSubscribe",
  "dc.chanUnsubscribe",
  "dc.tcSubscribe",
  "dc.tcUnsubscribe",
  "dc.tcTraceSync",
  "dc.tcTraceCallback",
  "dc.tcTracePromise",
  "process.onUncaughtException",
  "process.offUncaughtException",
  "process.onSignal",
  "process.offSignal",
  "process.onUnhandledRejection",
  "process.onRejectionHandled",
  "async.awaitDyn",
  "als.run",
  "als.exitRun",
  "dc.chanBindStore",
  "dc.chanRunStores",
  "http.resWriteHeadDyn",
  "http.resWriteContinue",
  "http.resWriteProcessing",
  "http.resWriteEarlyHints",
  "http.validateHeaderName",
  "http.validateHeaderValue",
  "http.serverTimeoutGet",
  "http.serverTimeoutOptionSet",
  "net.sockSetEncoding",
  "http.reqSetEncoding",
  "fs.readFileSyncBuf",
  "fs.readFileSyncDyn",
  "fs.readFileEncoded",
  "fs.readFdEncoded",
  // tls/https runtime options records: the walks throw the catchable
  // runtime fence for out-of-bounds members and non-PEM values (the
  // divergence-66 stance).
  "tls.pemDyn",
  "tls.createServerDyn",
  "tls.createSecureContextDyn",
  "tls.caCertsChk",
  "tls.createServerDynCb",
  "https.createServerDyn",
  "https.createServerDynCb",
  "http2.createSecureServerDyn",
  "http2.createSecureServerDynCb",
  "tls.connect",
  "tls.connectCb",
  // The CA-store surface: an unknown getCACertificates type throws
  // Node's ERR_INVALID_ARG_VALUE TypeError; setDefaultCACertificates
  // throws Node's ERR_CRYPTO_OPERATION_FAILED on a certificate-free
  // array.
  "tlsca.get",
  "tlsca.set",
  // EventEmitter dispatch runs user listeners synchronously (emit), and
  // the mutation forms fire the newListener/removeListener meta events —
  // any of them can throw. emitError additionally THROWS its payload when
  // 'error' has no listener, Node's unhandled-'error' contract.
  "emitter.emit",
  "emitter.emitFlex",
  "emitter.emitError",
  "emitter.on",
  "emitter.off",
  "emitter.checkListener",
  "emitter.onDyn",
  "emitter.onFlex",
  "emitter.offDyn",
  "emitter.onData",
  "emitter.onDataDyn",
  "emitter.emitData",
  "readable.nextChunk",
  "readable.nextChunkDyn",
  // The checked-dynamic chunk forms throw Node's ERR_INVALID_ARG_TYPE
  // chunk TypeError on a non-string/Buffer dyn kind.
  "net.sockWriteDyn",
  "net.sockEndDyn",
  "http.resWriteDyn",
  "http.resEndDyn",
  "http.resAddTrailers",
  "http.resFlushHeaders",
  "http.resUncork",
  "http.resWriteHead",
  "http.resWriteHeadN",
  "http.resWriteHeadPairs",
  "http.resWrite",
  "http.resWriteBytes",
  "http.resEnd",
  "http.resEndStr",
  "http.resEndBytes",
  "http.clientWriteDyn",
  "http.clientEndDyn",
  "http.clientAddTrailers",
  "http.clientFlushHeaders",
  "http.clientUncork",
  "http.clientWrite",
  "http.clientWriteBytes",
  "http.clientEnd",
  "http.clientEndStr",
  "http.clientEndBytes",
  // The URL-string client form throws catchably on an unparsable input
  // ("Invalid URL") or a non-http scheme (ERR_INVALID_PROTOCOL).
  "http.requestUrl",
  "http.requestUrlCb",
  // The h2 client's throwing entries: connect on a bad/non-http
  // authority (ERR_INVALID_URL / ERR_INVALID_PROTOCOL), request on a
  // closed/destroyed session (ERR_HTTP2_INVALID_SESSION), setEncoding on
  // an unknown name (ERR_UNKNOWN_ENCODING). Event fires run user code
  // synchronously (the stream-operations stance below), so the data/
  // write paths that can fire inline join too.
  "http2.connect",
  "http2.connectCb",
  "http2.sessionRequest",
  "http2.streamSetEncoding",
  "http2.streamRespond",
  "http2.streamWrite",
  "http2.streamWriteBytes",
  "http2.streamEnd",
  "http2.streamEndStr",
  "http2.streamEndBytes",
  "emitter.removeAll",
  // Stream operations run user code synchronously (option callbacks and
  // 'data'/'drain'/... listeners on the caller's stack, like emit) — any
  // of them may leave a listener's throw pending. destroy with no 'error'
  // listener throws the payload itself (the emitter.emitError contract).
  // The dyn-options constructors walk the record at runtime: a consumed-
  // but-unlowered option (objectMode, construct, ...) throws the compile
  // fence's runtime twin; a bad encoding throws ERR_UNKNOWN_ENCODING.
  "stream.finished",
  "stream.finishedDyn",
  "stream.pipeline",
  "stream.pipelineDyn",
  "sp.finished",
  "sp.pipeline",
  "sc.text",
  "sc.json",
  "sc.buffer",
  "readable.newDyn",
  "writable.newDyn",
  "duplex.newDyn",
  "transform.newDyn",
  "passthrough.newDyn",
  "readable.initDyn",
  "writable.initDyn",
  "duplex.initDyn",
  "transform.initDyn",
  "passthrough.initDyn",
  "readable.push",
  "readable.pushStr",
  "readable.pushStrEnc",
  "readable.pushNull",
  "readable.pushU",
  "readable.pushDyn",
  "readable.unshift",
  "readable.unshiftStr",
  "readable.read",
  "readable.readDyn",
  "stream.onDyn",
  "readable.resume",
  "readable.pipe",
  "readable.unpipe",
  "writable.write",
  "writable.writeStr",
  "writable.writeU",
  "writable.writeDyn",
  "writable.end",
  "writable.uncork",
  "stream.destroy",
  "stream.destroyErr",
  "stream.iteratorClose",
  // setMaxListeners(n) throws Node's ERR_OUT_OF_RANGE RangeError for
  // negative/NaN arguments; the static form's default-max write validates
  // identically (Node's validateNumber(n, "setMaxListeners", 0)).
  "emitter.setMax",
  "emitter.setDefaultMax",
  // The createConnection request forms run the caller's dialer closure
  // synchronously — a throw there propagates like Node's.
  "http.requestConn",
  "http.requestConnCb",
  "process.kill",
  "process.killNum",
  "process.setExitCode",
  // cpuUsage(prev)'s field validation: negative/non-finite prev fields
  // throw Node's ERR_INVALID_ARG_VALUE RangeError, catchably.
  "process.cpuPrevValidate",
  // Non-TTY stdin: Node's stdin has no setRawMode member, so the call is
  // the exact catchable TypeError.
  "process.stdinSetRawMode",
  // The unguarded h2-only stream call: always throws Node's TypeError.
  "http2.streamUndefCall",
  "http.reqH2StreamOrThrow",
  // A read of a declare-d const nothing defines: always throws Node's
  // catchable ReferenceError.
  "global.undefRead",
  // The compiler-resolved Node-parity throw: always throws, catchably.
  "error.nodeThrow",
  // USVString coercion runs user toString/valueOf — throws propagate.
  "dyn.toStringCoerce",
  "dyn.stringConstructor",
  "dyn.propertyKey",
  "dyn.toNumeric",
  "dyn.increment",
  // Error messages use the same coercion protocol before installing cause.
  "error.newOptions",
  "error.ctorOptions",
  "error.toString",
  "error.stack",
  "error.cause",
  "error.setCause",
  "error.deleteCause",
  "dyn.objectTag",
  // Numeric coercion runs user valueOf/toString — throws propagate.
  "dyn.numberConstructor",
  "dyn.bigintConstructor",
  "dyn.toNumberCoerce",
  "dyn.add",
  "dyn.arithmetic",
  "dyn.compare",
  "dyn.bitwise",
  "dyn.proxyNew",
  "dyn.classBasePrototype",
  "dyn.classInherit",
  "dyn.classSuper",
  "dyn.hasKey",
  "child.kill",
  // The caller's lookup runs synchronously inside the connect call — a
  // throw there propagates like Node's.
  "net.connectLookup",
  "cp.execSync",
  "cp.execCapture",
  // The client request constructors validate the method token
  // synchronously (Node's ClientRequest ctor throw:
  // ERR_INVALID_HTTP_TOKEN).
  "http.request",
  "http.requestCb",
  "http.requestConn",
  "http.requestConnCb",
  // The agent rows add the runtime agent-value gates (a non-Agent value
  // is Node's ERR_INVALID_ARG_TYPE); agentNew's keepAlive: true throws
  // the named pooling fence.
  "http.agentNew",
  "http.requestAgent",
  "http.requestAgentCb",
  "https.requestAgent",
  "https.requestAgentCb",
  "https.request",
  "https.requestCb",
  // The URL-string form's parse, exactly http.requestUrl's (an
  // unparsable input, or a scheme that is not https).
  "https.requestUrl",
  "https.requestUrlCb",
  "https.requestFn",
  "https.requestFnCb",
  "rl.question",
  "island.eval",
  "island.import",
  "island.castFail",
  "json.parse",
  "json.parseReviver",
  "json.stringifyReplacer",
  "json.stringifyValue",
  "date.nativeNew",
  "date.checkedValue",
  "util.parseArgs",
  "util.parseEnv",
  "util.getSystemErrorName",
  "util.getSystemErrorMessage",
  "util.stripVTControlCharacters",
  "util.isDeepStrictEqual",
  "util.styleText",
  "util.toUSVString",
  // decodeURIComponent throws the spec's URIError on bad hex/invalid
  // UTF-8 octets (encodeURIComponent never throws — see the IrLibFn doc).
  "str.decodeUriComponent",
  "str.decodeUri",
  // The base64 globals: atob/btoa throw the catchable DOMException
  // InvalidCharacterError on malformed input; the zero-argument form
  // always throws Node's TypeError [ERR_MISSING_ARGS].
  "str.atob",
  "str.btoa",
  "str.b64Missing",
  // queueMicrotask's checked-dynamic form throws ERR_INVALID_ARG_TYPE
  // synchronously on a non-function argument (the closure form never
  // throws — the callback's own throw surfaces at drain, uncaught).
  "timers.queueMicrotaskDyn",
  // structuredClone: option validation throws Node's TypeErrors,
  // functions/handles the spec's DataCloneError, cycles the scriptc
  // fence; the zero-argument form always throws ERR_MISSING_ARGS. The
  // DOMException clone shares the option validation.
  "dyn.structuredClone",
  "dyn.cloneMissing",
  "dyn.cloneTransferFail",
  // the dyn Object walks throw on null/undefined receivers
  "dyn.objKeys",
  "dyn.forInKeys",
  "dyn.hasOwn",
  "dyn.propertyIsEnumerable",
  "dyn.assign",
  "dyn.copyDataProperties",
  "dyn.objectRest",
  // variadic Object.assign: spread flattening throws V8's spread-call
  // TypeErrors; the final copy throws ToObject on a nullish target
  "dyn.packPushSpread",
  "dyn.packPushSpreadIter",
  "dyn.assignAll",
  "dyn.objCreate",
  "dyn.objCreateWithProperties",
  "dyn.getPrototype",
  "dyn.setPrototype",
  "dyn.getOwnPropertyNames",
  "dyn.ownKeys",
  "dyn.getOwnPropertySymbols",
  "dyn.getOwnPropertyDescriptors",
  "dyn.preventExtensions",
  "dyn.isExtensible",
  "dyn.seal",
  "dyn.isSealed",
  "dyn.objValues",
  "dyn.objEntries",
  "error.domClone",
  // new RegExp compiles the pattern eagerly: an invalid pattern or flag
  // throws Node's catchable SyntaxError at construction.
  "regex.new",
  "regex.resetLastIndex",
  "regex.newChecked",
  "regex.replaceCallback",
  "dyn.keySet",
  "dyn.keySetComputed",
  "process.builtinId",
  "process.builtinModule",
  "process.builtinUnsupported",
  "fs.callbackValue",
  "fs.callbackCall",
  "dyn.keyDelete",
  "dyn.keyDeleteComputed",
  "dyn.hasKeyComputed",
  "dyn.hasOwnComputed",
  "dyn.propertyIsEnumerableComputed",
  // the destructuring pack throws V8's TypeError on non-iterable dyn kinds
  "dyn.iterPack",
  "dyn.arrayFromIterator",
  "dyn.iterator",
  "dyn.iteratorResult",
  "dyn.iteratorStep",
  "dyn.mapSeedEntries",
  "dyn.mapSeedEntry",
  "dyn.freeze",
  "dyn.isFrozen",
  "dyn.toString",
  "string.fromCodePoint",
  "dyn.defineProps",
  "dyn.definePrototypeProps",
  "dyn.bagGet",
  "dyn.bagSet",
  "dyn.defineProperty",
  "dyn.getOwnPropertyDescriptor",
  "dyn.arrayProtoCall",
  "process.chdir",
  "process.loadEnvFile",
  "fs.realpathSync",
  "fs.realpathNativeSync",
  "fs.readFileSync",
  "fs.writeFileSync",
  "fs.appendFileSync",
  "fs.mkdirSync",
  "fs.rmSync",
  "fs.rmdirSync",
  "fs.readdirSync",
  "fs.readdirTypesSync",
  "url.new",
  "url.newBase",
  "url.set",
  "url.setChecked",
  "url.fileURLToPathUrl",
  "url.fileURLToPathChecked",
  "url.fileURLToPathOptions",
  "url.fileURLToPathBuffer",
  "url.pathToFileURLChecked",
  "url.fileURLToPathStr",
  // The win32-target flavor of pathToFileURL (same runtime entry point —
  // the bridge dispatches by the binary's platform): Node's win32 arm
  // raises ERR_INVALID_ARG_VALUE TypeErrors for malformed UNC inputs, so
  // only THIS flavor seeds may-throw — posix emission stays untouched.
  "url.pathToFileURLWin32",
  "url.pathToFileURLPlatform",
  // URLSearchParams from a string[][]: Node's ERR_INVALID_TUPLE TypeError
  // on a row that is not a [name, value] pair. The rest of the sp family
  // never throws.
  "sp.fromPairs",
  "sp.newChecked",
  "fs.statSync",
  "crypto.randomBytesToString",
  "crypto.randomBytes",
  "crypto.hashDigestStr",
  "crypto.hashDigestBytes",
  "crypto.hashNew",
  "crypto.hmacNewStr",
  "crypto.hmacNewBytes",
  "crypto.hashUpdateStr",
  "crypto.hashUpdateBytes",
  "crypto.hmacUpdateStr",
  "crypto.hmacUpdateBytes",
  "crypto.hashCopy",
  "crypto.hashDigestString",
  "crypto.hashDigestBuffer",
  "crypto.hmacDigestString",
  "crypto.hmacDigestBuffer",
  "crypto.timingSafeEqual",
  "crypto.randomFill",
  "crypto.randomFillRest",
  "crypto.randomInt",
  "crypto.pbkdf2",
  "crypto.randomBytesCb",
  "crypto.pbkdf2Cb",
  "crypto.hkdf",
  "crypto.hkdfCb",
  "crypto.scrypt",
  "crypto.scryptCb",
  "buffer.concat",
  "buffer.concatLen",
  "buffer.fromDyn",
  "buffer.fromStrChecked",
  // The checked-dynamic compare/equals validators: Node's argument
  // ladders throw ERR_INVALID_ARG_TYPE / ERR_OUT_OF_RANGE catchably.
  "buffer.compareChk",
  "bytes.equalsChk",
  "bytes.compareChk",
  "buffer.newStringFail",
  "fs.toUnixTimestamp",
  "fs.existsChk",
  "fs.mkdtempChk",
  "fs.mkdtempSyncChk",
  "fs.readFileChk",
  "fs.opendirChk",
  "fs.watchFileChk",
  "fs.lchmodChk",
  "fs.lchmodSyncChk",
  "fsp.lchmodChk",
  "fs.readChk",
  "fs.streamOptsChk",
  "net.connectAttempt",
  "net.connectOptsChk",
  "net.setAutoSelTimeout",
  "error.argTypeThrow",
  "error.propTypeThrow",
  "emitter.setMaxChk",
  "emitter.setDefaultMaxChk",
  "fs.readFileSyncBytes",
  "fs.writeFileSyncBytes",
  "fs.appendFileSyncBytes",
  "zlib.inflateSync",
  "zlib.inflateRawSync",
  "zlib.gunzipSync",
  "zlib.unzipSync",
  "zlib.crc32",
  "date.toISOString",
  "date.toISOStringValue",
  "fs.mkdirRecursiveSync",
  "fs.rmOptsSync",
  "fs.rmRetrySync",
  "fs.mkdtempSync",
  "fs.accessSync",
  "fs.readFdSync",
  "fs.readFdSyncBytes",
  // node:dgram state errors (Node throws synchronously): bind on a bound
  // socket, connect on a connected one, send/close/address on a closed or
  // never-bound one.
  "dgram.bind",
  "dgram.bindCb",
  "dgram.connect",
  "dgram.connectCb",
  "dgram.sendStr",
  "dgram.sendBytes",
  "dgram.sendChk",
  "dgram.address",
  "dgram.close",
  "dgram.closeCb",
  // The assert surface: every entry point except sameValue, bytesDeepEq,
  // and the shape accumulator's begin/slot/test calls throws the
  // catchable AssertionError on failure.
  "assert.ok",
  "assert.eqF64",
  "assert.eqBigInt",
  "assert.eqStr",
  "assert.eqBool",
  "assert.eqSym",
  "assert.eqDyn",
  "assert.looseResult",
  "assert.deepResult",
  "assert.match",
  "assert.refEqBytes",
  "assert.refEqFn",
  "assert.throwsNone",
  "assert.throwsMismatch",
  "assert.throwsRegex",
  "assert.shapeEnd",
  "assert.unwantedRejection",
  "assert.unwantedError",
  "assert.noErrorPredicate",
  "assert.regexDynTest",
  "assert.expectsErrDyn",
  "assert.ifErrorErr",
  "assert.ifErrorF64",
  "assert.ifErrorStr",
  "assert.ifErrorBool",
  "assert.ifErrorDyn",
  // util.inspect of an island `any` composite: the runtime tag is all
  // there is, so the honest answer is a catchable TypeError.
  "insp.jsval",
  // The wider sync fs slice: same catchable errno throws as the rest.
  "fs.unlinkSync",
  "fs.chmodSync",
  "fs.chownSync",
  "fs.copyFileSync",
  "fs.renameSync",
  "fs.lstatSync",
  "fs.fstatSync",
  "fs.fchmodSync",
  "fs.fsyncSync",
  "fs.fdatasyncSync",
  "fs.ftruncateSync",
  "fs.utimesSync",
  "fs.futimesSync",
  "fs.lutimesSync",
  "fs.readvSync",
  "fs.writevSync",
  "fs.linkSync",
  "fs.symlinkSync",
  "fs.readlinkSync",
  "fs.statfsSync",
  "fs.readlinkSyncStr",
  "fs.readlinkSyncBuffer",
  "fs.writeFileModeSync",
  "fs.mkdirModeSync",
  "fs.mkdirRecursiveModeSync",
  "fs.openSync",
  "fs.openNumericSync",
  "fs.readSync",
  "fs.writeSync",
  "fs.writeStrSync",
  "fs.closeSync",
  "fs.watch",
  "fs.watchCb",
  "crypto.x509Fingerprint",
  "crypto.x509FingerprintStr",
  "crypto.x509ValidFrom",
  "crypto.x509ValidFromStr",
  "crypto.x509ValidTo",
  "crypto.x509ValidToStr",
]);
